### PR TITLE
Update PyCharm to 2021.3.3

### PR DESCRIPTION
**Pull request by sheepman4267**
Update PyCharm to 2021.3.3

### CODE REVIEW

**Comment by Staudey** [comment]
Hey there!
Seems like @ahahn94 updated it in the meantime (as I said on IRC I was still waiting to give you time to do PyCharm-CE too). Thanks for the PR anyway. We'll beat him next time :smiley:

**Comment by ahahn94** [comment]
I‘m checking for updates to the JetBrains IDEs every saturday. In rare cases, I may postpone updates until monday if I didn’t have time for it 😄

**Comment by Staudey** [comment]
Thanks for the clarification! I wasn't sure about the release schedule for their IDEs and whether you might be on vacation/busy/etc. Would've checked that before merge in any case :smile_cat:

**Comment by sheepman4267** [comment]
Nice! Thanks @ahahn94. I'm perfectly happy to just jettison doing CE from my to-do list :grin: 

Sorry for stepping on your toes- I just didn't know the schedule, and it looked pretty easy. Figured I'd knock something off someone else's plate for once, instead of piling on.

**Pull request closed without merging**
