### PR TITLE
Synology drive client

### PR DESCRIPTION
**Pull request by L0g0ff**
Hi,
I create a working installer for the synology drive client. Synology drive client is the successor of cloud station drive.

You can test it for yourself:
sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/L0g0ff/3rd-party/master/network/download/synology-drive-client/pspec.xml
sudo eopkg it synology-drive-client*.eopkg;sudo rm synology-drive-client*.eopkg

I hope you can add this change to the official branch. This is the first time I create a debian to solus port. If I did something wrong please sent me what to do and I will fix it.

Kind regards,
Thomas

### CODE REVIEW

**Comment by DataDrake** [comment]
Straight from the README:

> **Note**: This repo will not accept NEW packages as we are replacing the majority of them in Solus with Snaps. After we have Snaps integrated in the Software Center we will begin forceful deprecation of this repository.

For anyone needing this client, it is available as a `flatpak`. However, we will not be adding it to Third Party.

**Comment by georgybog** [comment]
Why? Ocenaudio or bigwig not available on snap or flatpak

**Comment by DataDrake** [comment]
When Third Party was created, there were no alternatives. We didn't want Solus to end up with a wild west repository like an AUR, so we decided to maintain a curated selection of things that made sense. Years later, we have Snap, Flatpak, and AppImage covering a lot of the things that we had no choice but to support. We aren't killing off Third Party any time soon, but we certainly aren't going to add new things to it now that better alternatives exist. Doubly-so when they are already available on one of those platforms.

**Comment by L0g0ff** [comment]
> Straight from the README:
> 
> > **Note**: This repo will not accept NEW packages as we are replacing the majority of them in Solus with Snaps. After we have Snaps integrated in the Software Center we will begin forceful deprecation of this repository.
> 
> For anyone needing this client, it is available as a `flatpak`. However, we will not be adding it to Third Party.

My bad. I saw the readme after I did the pull request. 

I totally understand the switch from this 3rth party to flat from solus perspective. But most of the time I like distro packages more that flat/snap because of the (gui/hardware) integration.

Flat packages is how the dev want to see the program but a distro package is mostly better integrated.

But that's another discussion 😅

Keep up the good work!

**Pull request closed without merging**
